### PR TITLE
Add initial pre-commit and fix up and issues

### PR DESCRIPTION
**Pull request by ghost**
relates to #9

### CODE REVIEW

**Review by rpsene — APPROVED** [review]
LGTM

**Review by wmat — APPROVED** [review]
Thanks, Kevin.

**Comment by ghost** [comment]
Sorry about the forced pushing above, I didn't change anything but had forgot to do the `git commit -S` and at first I thought I only needed `git commit -s`  which is why there's multiple forced push.  I'll try not to make a mess of things next time 😉

**Comment by wmat** [comment]
No worries.

**Pull request merged**
